=== fermanzolido/L2C4/dist/game/data/xsd/classMaster.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="list">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="classMaster">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="classChangeOption" maxOccurs="unbounded" minOccurs="0">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="appliesTo">
											<xs:complexType>
												<xs:sequence>
													<xs:element type="xs:string" name="category" />
												</xs:sequence>
											</xs:complexType>
										</xs:element>
										<xs:element name="rewards" minOccurs="0">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="item" maxOccurs="unbounded" minOccurs="0">
														<xs:complexType>
															<xs:simpleContent>
																<xs:extension base="xs:string">
																	<xs:attribute type="xs:int" name="id" use="optional" />
																	<xs:attribute type="xs:byte" name="count" use="optional" />
																	<xs:attribute type="xs:byte" name="chance" use="optional" />
																</xs:extension>
															</xs:simpleContent>
														</xs:complexType>
													</xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
										<xs:element name="conditions" minOccurs="0">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="item" maxOccurs="unbounded" minOccurs="0">
														<xs:complexType>
															<xs:simpleContent>
																<xs:extension base="xs:string">
																	<xs:attribute type="xs:short" name="id" use="optional" />
																	<xs:attribute type="xs:int" name="count" use="optional" />
																	<xs:attribute type="xs:byte" name="chance" use="optional" />
																</xs:extension>
															</xs:simpleContent>
														</xs:complexType>
													</xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
									<xs:attribute type="xs:string" name="name" use="optional" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute type="xs:string" name="classChangeEnabled" />
						<xs:attribute type="xs:string" name="spawnClassMasters" />
						<xs:attribute type="xs:string" name="showPopupWindow" />
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== fermanzolido/L2C4/dist/game/config/ClassMaster.xml
<?xml version="1.0" encoding="utf-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../data/xsd/classMaster.xsd">
	<classMaster classChangeEnabled="true" spawnClassMasters="true" showPopupWindow="true">
		<classChangeOption name="Free">
			<appliesTo>
				<category>FIRST_CLASS_GROUP</category>
			</appliesTo>
		</classChangeOption>
		<classChangeOption name="1,000,000 Adena">
			<appliesTo>
				<category>SECOND_CLASS_GROUP</category>
			</appliesTo>
			<conditions>
				<item id="57" count="1000000" />
			</conditions>
		</classChangeOption>
		<!-- Example:
		<classChangeOption name="Pay Adena and Ancient Adena">
			<appliesTo>
				<category>THIRD_CLASS_GROUP</category>
			</appliesTo>
			<rewards>
				<item id="6622" count="1" /> Book of Giants
			</rewards>
			<conditions>
				<item id="57" count="3000000" />3 million Adena for third class
				<item id="5575" count="300000" />300k Ancient Adena for third class
			</conditions>
		</classChangeOption> -->
	</classMaster>
</list>
