=== fermanzolido/L2C4/dist/game/data/xsd/experienceLoss.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="list">
		<xs:complexType>
			<xs:sequence minOccurs="1" maxOccurs="1">
				<xs:element name="experience" minOccurs="1" maxOccurs="100">
					<xs:complexType>
						<xs:attribute name="level" use="required" type="xs:byte" />
						<xs:attribute name="val" use="required" type="xs:float" />
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== fermanzolido/L2C4/dist/game/data/stats/players/experienceLoss.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../xsd/experienceLoss.xsd">
	<experience level="1" val="10.0" />
	<experience level="2" val="9.875" />
	<experience level="3" val="9.75" />
	<experience level="4" val="9.625" />
	<experience level="5" val="9.5" />
	<experience level="6" val="9.375" />
	<experience level="7" val="9.25" />
	<experience level="8" val="9.125" />
	<experience level="9" val="9.0" />
	<experience level="10" val="8.875" />
	<experience level="11" val="8.75" />
	<experience level="12" val="8.625" />
	<experience level="13" val="8.5" />
	<experience level="14" val="8.375" />
	<experience level="15" val="8.25" />
	<experience level="16" val="8.125" />
	<experience level="17" val="8.0" />
	<experience level="18" val="7.875" />
	<experience level="19" val="7.75" />
	<experience level="20" val="7.625" />
	<experience level="21" val="7.5" />
	<experience level="22" val="7.375" />
	<experience level="23" val="7.25" />
	<experience level="24" val="7.125" />
	<experience level="25" val="7.0" />
	<experience level="26" val="6.875" />
	<experience level="27" val="6.75" />
	<experience level="28" val="6.625" />
	<experience level="29" val="6.5" />
	<experience level="30" val="6.375" />
	<experience level="31" val="6.25" />
	<experience level="32" val="6.125" />
	<experience level="33" val="6.0" />
	<experience level="34" val="5.875" />
	<experience level="35" val="5.75" />
	<experience level="36" val="5.625" />
	<experience level="37" val="5.5" />
	<experience level="38" val="5.375" />
	<experience level="39" val="5.25" />
	<experience level="40" val="5.125" />
	<experience level="41" val="5.0" />
	<experience level="42" val="4.875" />
	<experience level="43" val="4.75" />
	<experience level="44" val="4.625" />
	<experience level="45" val="4.5" />
	<experience level="46" val="4.375" />
	<experience level="47" val="4.25" />
	<experience level="48" val="4.125" />
	<experience level="49" val="4.0" />
	<experience level="50" val="4.0" />
	<experience level="51" val="4.0" />
	<experience level="52" val="4.0" />
	<experience level="53" val="4.0" />
	<experience level="54" val="4.0" />
	<experience level="55" val="4.0" />
	<experience level="56" val="4.0" />
	<experience level="57" val="4.0" />
	<experience level="58" val="4.0" />
	<experience level="59" val="4.0" />
	<experience level="60" val="4.0" />
	<experience level="61" val="4.0" />
	<experience level="62" val="4.0" />
	<experience level="63" val="4.0" />
	<experience level="64" val="4.0" />
	<experience level="65" val="4.0" />
	<experience level="66" val="4.0" />
	<experience level="67" val="4.0" />
	<experience level="68" val="4.0" />
	<experience level="69" val="4.0" />
	<experience level="70" val="4.0" />
	<experience level="71" val="4.0" />
	<experience level="72" val="4.0" />
	<experience level="73" val="4.0" />
	<experience level="74" val="4.0" />
	<experience level="75" val="4.0" />
	<experience level="76" val="2.5" />
	<experience level="77" val="2.0" />
	<experience level="78" val="1.5" />
	<experience level="79" val="1.0" />
	<experience level="80" val="1.0" />
</list>
