=== fermanzolido/L2C4/dist/game/data/xsd/npcs.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="list">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="npc" type="npcType" minOccurs="1" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="npcType">
		<xs:choice maxOccurs="unbounded" minOccurs="0">
			<xs:element name="acquire" type="acquireType" minOccurs="0" maxOccurs="1" />
			<xs:element name="ai" type="aiType" minOccurs="0" maxOccurs="1" />
			<xs:element name="collision" type="collisionType" minOccurs="0" maxOccurs="1" />
			<xs:element name="corpseTime" type="xs:nonNegativeInteger" minOccurs="0" maxOccurs="1" />
			<xs:element name="dropLists" minOccurs="0" maxOccurs="1">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="drop" minOccurs="0">
							<xs:complexType>
								<xs:sequence>
									<xs:element name="item" maxOccurs="unbounded" minOccurs="0">
										<xs:complexType>
											<xs:simpleContent>
												<xs:extension base="xs:string">
													<xs:attribute type="xs:int" name="id" use="required" />
													<xs:attribute type="xs:int" name="min" use="required" />
													<xs:attribute type="xs:int" name="max" use="required" />
													<xs:attribute type="xs:double" name="chance" use="required" />
												</xs:extension>
											</xs:simpleContent>
										</xs:complexType>
									</xs:element>
									<xs:element name="group" maxOccurs="unbounded" minOccurs="0">
										<xs:complexType>
											<xs:sequence>
												<xs:element name="item" maxOccurs="unbounded" minOccurs="0">
													<xs:complexType>
														<xs:simpleContent>
															<xs:extension base="xs:string">
																<xs:attribute type="xs:int" name="id" use="required" />
																<xs:attribute type="xs:int" name="min" use="required" />
																<xs:attribute type="xs:int" name="max" use="required" />
																<xs:attribute type="xs:double" name="chance" use="required" />
															</xs:extension>
														</xs:simpleContent>
													</xs:complexType>
												</xs:element>
											</xs:sequence>
											<xs:attribute type="xs:double" name="chance" use="optional" />
										</xs:complexType>
									</xs:element>
								</xs:sequence>
							</xs:complexType>
						</xs:element>
						<xs:element name="spoil" minOccurs="0">
							<xs:complexType>
								<xs:sequence>
									<xs:element name="item" maxOccurs="unbounded" minOccurs="0">
										<xs:complexType>
											<xs:simpleContent>
												<xs:extension base="xs:string">
													<xs:attribute type="xs:int" name="id" use="optional" />
													<xs:attribute type="xs:int" name="min" use="optional" />
													<xs:attribute type="xs:int" name="max" use="optional" />
													<xs:attribute type="xs:double" name="chance" use="optional" />
												</xs:extension>
											</xs:simpleContent>
										</xs:complexType>
									</xs:element>
								</xs:sequence>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="equipment" type="equipmentType" minOccurs="0" maxOccurs="1" />
			<xs:element name="exCrtEffect" type="xs:boolean" minOccurs="0" maxOccurs="1" />
			<xs:element name="parameters" type="parametersType" minOccurs="0" maxOccurs="1" />
			<xs:element name="race" type="xs:token" minOccurs="0" maxOccurs="1" />
			<xs:element name="sNpcPropHpRate" type="xs:decimal" minOccurs="0" maxOccurs="1" />
			<xs:element name="sex" type="xs:token" minOccurs="0" maxOccurs="1" />
			<xs:element name="shots" type="shotsType" minOccurs="0" maxOccurs="1" />
			<xs:element name="skillList" type="skillType" minOccurs="0" maxOccurs="1" />
			<xs:element name="stats" type="statsType" minOccurs="0" maxOccurs="1" />
			<xs:element name="status" type="statusType" minOccurs="0" maxOccurs="1" />
			<xs:element name="fakePlayer" type="fakePlayerParams" minOccurs="0" maxOccurs="1" />
		</xs:choice>
		<xs:attribute name="id" type="xs:positiveInteger" use="required" />
		<xs:attribute name="displayId" type="xs:positiveInteger" />
		<xs:attribute name="level" type="xs:byte" />
		<xs:attribute name="type" type="xs:token" />
		<xs:attribute name="name" type="xs:string" />
		<xs:attribute name="usingServerSideName" type="xs:boolean" />
		<xs:attribute name="title" type="xs:string" />
		<xs:attribute name="usingServerSideTitle" type="xs:boolean" />
	</xs:complexType>
	
	<xs:complexType name="acquireType">
		<xs:attribute name="exp" type="xs:decimal" />
		<xs:attribute name="sp" type="xs:decimal" />
	</xs:complexType>
	
	<xs:complexType name="aiType">
		<xs:all>
			<xs:element name="skill" minOccurs="0" maxOccurs="1">
				<xs:complexType>
					<xs:attribute name="minChance" type="xs:nonNegativeInteger" />
					<xs:attribute name="maxChance" type="xs:nonNegativeInteger" />
					<xs:attribute name="primaryId" type="xs:nonNegativeInteger" />
					<xs:attribute name="shortRangeId" type="xs:nonNegativeInteger" />
					<xs:attribute name="shortRangeChance" type="xs:nonNegativeInteger" />
					<xs:attribute name="longRangeId" type="xs:nonNegativeInteger" />
					<xs:attribute name="longRangeChance" type="xs:nonNegativeInteger" />
				</xs:complexType>
			</xs:element>
			<xs:element name="clanList" minOccurs="0" maxOccurs="1">
				<xs:complexType>
					<xs:choice minOccurs="1" maxOccurs="unbounded">
						<xs:element name="clan" type="xs:token" />
						<xs:element name="ignoreNpcId" type="xs:nonNegativeInteger" />
					</xs:choice>
				</xs:complexType>
			</xs:element>
		</xs:all>
		<xs:attribute name="type" type="xs:token" />
		<xs:attribute name="aggroRange" type="xs:nonNegativeInteger" />
		<xs:attribute name="clanHelpRange" type="xs:nonNegativeInteger" />
		<xs:attribute name="isChaos" type="xs:boolean" />
		<xs:attribute name="isAggressive" type="xs:boolean" />
	</xs:complexType>
	
	<xs:complexType name="collisionType">
		<xs:all>
			<xs:element name="radius" type="size" minOccurs="0" maxOccurs="1" />
			<xs:element name="height" type="size" minOccurs="0" maxOccurs="1" />
		</xs:all>
	</xs:complexType>
	
	<xs:complexType name="size">
		<xs:attribute name="normal" type="xs:decimal" />
		<xs:attribute name="grown" type="xs:decimal" />
	</xs:complexType>
	
	<xs:complexType name="dropListsType">
		<xs:all>
			<xs:element name="drop" type="dropList" minOccurs="0" maxOccurs="1" />
			<xs:element name="spoil" type="dropList" minOccurs="0" maxOccurs="1" />
		</xs:all>
	</xs:complexType>
	
	<xs:complexType name="dropList">
		<xs:choice minOccurs="1" maxOccurs="unbounded">
			<xs:element name="item" type="dropListItem" />
		</xs:choice>
	</xs:complexType>
	
	<xs:complexType name="dropListItem">
		<xs:attribute name="id" type="xs:positiveInteger" use="required" />
		<xs:attribute name="min" type="xs:nonNegativeInteger" />
		<xs:attribute name="max" type="xs:positiveInteger" />
		<xs:attribute name="chance" type="xs:decimal" />
	</xs:complexType>
	
	<xs:complexType name="equipmentType">
		<xs:attribute name="chest" type="xs:nonNegativeInteger" />
		<xs:attribute name="rhand" type="xs:nonNegativeInteger" />
		<xs:attribute name="lhand" type="xs:nonNegativeInteger" />
		<xs:attribute name="weaponEnchant" type="xs:nonNegativeInteger" />
	</xs:complexType>
	
	<xs:complexType name="parametersType">
		<xs:choice minOccurs="1" maxOccurs="unbounded">
			<xs:element name="param">
				<xs:complexType>
					<xs:attribute name="name" type="xs:token" use="required" />
					<xs:attribute name="value" type="xs:string" use="required" />
				</xs:complexType>
			</xs:element>
			<xs:element name="skill">
				<xs:complexType>
					<xs:attribute name="name" type="xs:token" use="required" />
					<xs:attribute name="id" type="xs:positiveInteger" use="required" />
					<xs:attribute name="level" type="xs:positiveInteger" use="required" />
				</xs:complexType>
			</xs:element>
			<xs:element name="minions">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="npc" minOccurs="1" maxOccurs="unbounded">
							<xs:complexType>
								<xs:attribute name="id" type="xs:positiveInteger" use="required" />
								<xs:attribute name="count" type="xs:positiveInteger" use="required" />
								<xs:attribute name="max" type="xs:positiveInteger" use="optional" />
								<xs:attribute name="respawnTime" type="xs:nonNegativeInteger" use="required" />
								<xs:attribute name="weightPoint" type="xs:integer" use="optional" />
							</xs:complexType>
						</xs:element>
					</xs:sequence>
					<xs:attribute name="name" type="xs:token" use="required" />
				</xs:complexType>
			</xs:element>
		</xs:choice>
	</xs:complexType>

	<xs:complexType name="shotsType">
		<xs:attribute name="soul" type="xs:nonNegativeInteger" />
		<xs:attribute name="spirit" type="xs:nonNegativeInteger" />
		<xs:attribute name="shotChance" type="xs:nonNegativeInteger" />
		<xs:attribute name="spiritChance" type="xs:nonNegativeInteger" />
	</xs:complexType>

	<xs:complexType name="skillType">
		<xs:sequence>
			<xs:element name="skill" minOccurs="1" maxOccurs="unbounded">
				<xs:complexType>
					<xs:attribute name="id" type="xs:nonNegativeInteger" use="required" />
					<xs:attribute name="level" type="xs:nonNegativeInteger" use="required" />
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="statsType">
		<xs:choice maxOccurs="unbounded" minOccurs="0">
			<xs:element name="vitals" minOccurs="0" maxOccurs="1">
				<xs:complexType>
					<xs:attribute name="hp" type="xs:decimal" />
					<xs:attribute name="hpRegen" type="xs:decimal" />
					<xs:attribute name="mp" type="xs:decimal" />
					<xs:attribute name="mpRegen" type="xs:decimal" />
				</xs:complexType>
			</xs:element>
			<xs:element name="attack" minOccurs="0" maxOccurs="1">
				<xs:complexType>
					<xs:attribute name="physical" type="xs:decimal" />
					<xs:attribute name="magical" type="xs:decimal" />
					<xs:attribute name="random" type="xs:nonNegativeInteger" />
					<xs:attribute name="critical" type="xs:nonNegativeInteger" />
					<xs:attribute name="accuracy" type="xs:decimal" />
					<xs:attribute name="attackSpeed" type="xs:nonNegativeInteger" />
					<xs:attribute name="reuseDelay" type="xs:nonNegativeInteger" />
					<xs:attribute name="type">
						<xs:simpleType>
							<xs:restriction base="xs:string">
								<xs:enumeration value="SWORD" />
								<xs:enumeration value="BLUNT" />
								<xs:enumeration value="DAGGER" />
								<xs:enumeration value="BOW" />
								<xs:enumeration value="DUAL" />
								<xs:enumeration value="POLE" />
								<xs:enumeration value="DUALFIST" />
								<xs:enumeration value="FIST" />
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
					<xs:attribute name="range" type="xs:nonNegativeInteger" />
					<xs:attribute name="distance" type="xs:nonNegativeInteger" />
					<xs:attribute name="width" type="xs:nonNegativeInteger" />
				</xs:complexType>
			</xs:element>
			<xs:element name="defence" minOccurs="0" maxOccurs="1">
				<xs:complexType>
					<xs:attribute name="physical" type="xs:decimal" />
					<xs:attribute name="magical" type="xs:decimal" />
					<xs:attribute name="evasion" type="xs:integer" />
					<xs:attribute name="shield" type="xs:nonNegativeInteger" />
					<xs:attribute name="shieldRate" type="xs:nonNegativeInteger" />
				</xs:complexType>
			</xs:element>
			<xs:element name="attribute" minOccurs="0" maxOccurs="1">
				<xs:complexType>
					<xs:all>
						<xs:element name="attack" minOccurs="0" maxOccurs="1">
							<xs:complexType>
								<xs:attribute name="type">
									<xs:simpleType>
										<xs:restriction base="xs:string">
											<xs:enumeration value="FIRE" />
											<xs:enumeration value="WATER" />
											<xs:enumeration value="WIND" />
											<xs:enumeration value="EARTH" />
											<xs:enumeration value="DARK" />
											<xs:enumeration value="HOLY" />
										</xs:restriction>
									</xs:simpleType>
								</xs:attribute>
								<xs:attribute name="value" type="xs:nonNegativeInteger" />
							</xs:complexType>
						</xs:element>
						<xs:element name="defence" minOccurs="0" maxOccurs="1">
							<xs:complexType>
								<xs:attribute name="fire" type="xs:integer" />
								<xs:attribute name="water" type="xs:integer" />
								<xs:attribute name="wind" type="xs:integer" />
								<xs:attribute name="earth" type="xs:integer" />
								<xs:attribute name="holy" type="xs:integer" />
								<xs:attribute name="dark" type="xs:integer" />
								<xs:attribute name="default" type="xs:integer" />
							</xs:complexType>
						</xs:element>
					</xs:all>
				</xs:complexType>
			</xs:element>
			<xs:element name="speed" minOccurs="0" maxOccurs="1">
				<xs:complexType>
					<xs:all>
						<xs:element name="walk" minOccurs="0" maxOccurs="1">
							<xs:complexType>
								<xs:attribute name="ground" type="xs:decimal" />
								<xs:attribute name="swim" type="xs:decimal" />
								<xs:attribute name="fly" type="xs:decimal" />
							</xs:complexType>
						</xs:element>
						<xs:element name="run" minOccurs="0" maxOccurs="1">
							<xs:complexType>
								<xs:attribute name="ground" type="xs:decimal" />
								<xs:attribute name="swim" type="xs:decimal" />
								<xs:attribute name="fly" type="xs:decimal" />
							</xs:complexType>
						</xs:element>
					</xs:all>
				</xs:complexType>
			</xs:element>
			<xs:element name="hitTime" type="xs:nonNegativeInteger" minOccurs="0" maxOccurs="1" />
		</xs:choice>
		<xs:attribute name="str" type="xs:nonNegativeInteger" />
		<xs:attribute name="int" type="xs:nonNegativeInteger" />
		<xs:attribute name="dex" type="xs:nonNegativeInteger" />
		<xs:attribute name="wit" type="xs:nonNegativeInteger" />
		<xs:attribute name="con" type="xs:nonNegativeInteger" />
		<xs:attribute name="men" type="xs:nonNegativeInteger" />
	</xs:complexType>
	
	<xs:complexType name="statusType">
		<xs:attribute name="unique" type="xs:boolean" />
		<xs:attribute name="attackable" type="xs:boolean" />
		<xs:attribute name="talkable" type="xs:boolean" />
		<xs:attribute name="targetable" type="xs:boolean" />
		<xs:attribute name="undying" type="xs:boolean" />
		<xs:attribute name="showName" type="xs:boolean" />
		<xs:attribute name="randomWalk" type="xs:boolean" />
		<xs:attribute name="randomAnimation" type="xs:boolean" />
		<xs:attribute name="flying" type="xs:boolean" />
		<xs:attribute name="canMove" type="xs:boolean" />
		<xs:attribute name="noSleepMode" type="xs:boolean" />
		<xs:attribute name="passableDoor" type="xs:boolean" />
		<xs:attribute name="hasSummoner" type="xs:boolean" />
		<xs:attribute name="canBeSown" type="xs:boolean" />
	</xs:complexType>
	
	<xs:complexType name="fakePlayerParams">
		<xs:attribute name="classId" type="xs:int" />
		<xs:attribute name="hair" type="xs:int" />
		<xs:attribute name="hairColor" type="xs:int" />
		<xs:attribute name="face" type="xs:int" />
		<xs:attribute name="nameColor" type="xs:int" />
		<xs:attribute name="titleColor" type="xs:int" />
		<xs:attribute name="equipHead" type="xs:int" />
		<xs:attribute name="equipRHand" type="xs:int" />
		<xs:attribute name="equipLHand" type="xs:int" />
		<xs:attribute name="equipGloves" type="xs:int" />
		<xs:attribute name="equipChest" type="xs:int" />
		<xs:attribute name="equipLegs" type="xs:int" />
		<xs:attribute name="equipFeet" type="xs:int" />
		<xs:attribute name="equipCloak" type="xs:int" />
		<xs:attribute name="equipHair" type="xs:int" />
		<xs:attribute name="equipHair2" type="xs:int" />
		<xs:attribute name="agathionId" type="xs:int" />
		<xs:attribute name="weaponEnchantLevel" type="xs:int" />
		<xs:attribute name="armorEnchantLevel" type="xs:int" />
		<xs:attribute name="fishing" type="xs:boolean" />
		<xs:attribute name="baitLocationX" type="xs:int" />
		<xs:attribute name="baitLocationY" type="xs:int" />
		<xs:attribute name="baitLocationZ" type="xs:int" />
		<xs:attribute name="recommends" type="xs:int" />
		<xs:attribute name="nobleLevel" type="xs:int" />
		<xs:attribute name="hero" type="xs:boolean" />
		<xs:attribute name="clanId" type="xs:int" />
		<xs:attribute name="pledgeStatus" type="xs:int" />
		<xs:attribute name="sitting" type="xs:boolean" />
		<xs:attribute name="privateStoreType" type="xs:int" />
		<xs:attribute name="privateStoreMessage" type="xs:string" />
		<xs:attribute name="fakePlayerTalkable" type="xs:boolean" />
	</xs:complexType>
</xs:schema>

=== fermanzolido/L2C4/dist/game/data/stats/npcs/custom/ctf_event.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../xsd/npcs.xsd">
	<npc id="70012" displayId="31226" name="Manager" usingServerSideName="true" title="CtF Event" usingServerSideTitle="true" type="Folk">
		<race>HUMAN</race>
		<sex>MALE</sex>
		<stats>
			<vitals hp="2444.46819" hpRegen="7.5" mp="1345.8" mpRegen="2.7" />
			<attack physical="688.86373" magical="470.40463" random="30" critical="4" accuracy="95" attackSpeed="253" type="SWORD" range="40" distance="80" width="120" />
			<defence physical="295.91597" magical="216.53847" />
			<speed>
				<walk ground="40" />
				<run ground="120" />
			</speed>
		</stats>
		<status attackable="false" />
		<collision>
			<radius normal="8" />
			<height normal="23" />
		</collision>
	</npc>
	<npc id="82016" displayId="35062" name="Blue" usingServerSideName="true" title="" usingServerSideTitle="true" type="Folk">
		<race>ETC</race>
		<sex>ETC</sex>
		<stats>
			<vitals hp="2444.46819" hpRegen="7.5" mp="1345.8" mpRegen="2.7" />
			<attack physical="688.86373" magical="470.40463" random="30" critical="4" accuracy="95" attackSpeed="253" type="SWORD" range="40" distance="80" width="120" />
			<defence physical="295.91597" magical="216.53847" />
			<speed>
				<walk ground="40" />
				<run ground="120" />
			</speed>
		</stats>
		
		<status attackable="false" showName="true" canMove="false" />
		<collision>
			<radius normal="10" />
			<height normal="80" />
		</collision>
	</npc>
	<npc id="82017" displayId="35062" name="Red" usingServerSideName="true" title="" usingServerSideTitle="true" type="Folk">
		<race>ETC</race>
		<sex>ETC</sex>
		<stats>
			<vitals hp="2444.46819" hpRegen="7.5" mp="1345.8" mpRegen="2.7" />
			<attack physical="688.86373" magical="470.40463" random="30" critical="4" accuracy="95" attackSpeed="253" type="SWORD" range="40" distance="80" width="120" />
			<defence physical="295.91597" magical="216.53847" />
			<speed>
				<walk ground="40" />
				<run ground="120" />
			</speed>
		</stats>
		<status attackable="false" showName="true" canMove="false" />
		<collision>
			<radius normal="10" />
			<height normal="80" />
		</collision>
	</npc>
	<npc id="82018" displayId="31226" name="Manager" usingServerSideName="true" title="CtF Manager" usingServerSideTitle="false" type="Folk">
		<race>ETC</race>
		<sex>ETC</sex>
		<stats>
			<vitals hp="2444.46819" hpRegen="7.5" mp="1345.8" mpRegen="2.7" />
			<attack physical="688.86373" magical="470.40463" random="30" critical="4" accuracy="95" attackSpeed="253" type="SWORD" range="40" distance="80" width="120" />
			<defence physical="295.91597" magical="216.53847" />
			<speed>
				<walk ground="40" />
				<run ground="120" />
			</speed>
		</stats>
		<status attackable="false" showName="false" targetable="false" />
		<collision>
			<radius normal="30" />
			<height normal="31" />
		</collision>
	</npc>
</list>
